# :schema node_modules/wrangler/config-schema.json
name = "get-things-done-dev"
compatibility_date = "2024-11-06"
# pages_build_output_dir = ".svelte-kit/cloudflare"
main = "./.cloudflare/worker.js"
workers_dev = false

site.bucket = "./.cloudflare/public"

build.command = "bun run build"

compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

# ####### DEV environment config ########
[route]
pattern = "dev.get-things-done.app"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "dev.get-things-done"
database_id = "11b5ed69-836e-4d8e-a86d-39ba95a55550"

[[kv_namespaces]]
binding = "session"
id = "db829708b9ca408ba101569b9eb670f5"

# ####### PREVIEW environment config ########
[env.next]
name = "get-things-done-next"

[env.next.route]
pattern = "next.get-things-done.app"
custom_domain = true

[[env.next.d1_databases]]
binding = "DB"
database_name = "next.get-things-done"
database_id = "4460981c-d938-4be5-8e81-fa5f662fb50d"

[[env.next.kv_namespaces]]
binding = "session"
id = "29c78a613ba74a8fa30ac1188ea2a295"

# ####### PRODUCTION environment config ########
[env.prod]
name = "get-things-done"

[env.prod.route]
pattern = "get-things-done.app"
custom_domain = true

[[env.prod.d1_databases]]
binding = "DB"
database_name = "get-things-done"
database_id = "306ca8ef-80ae-44e5-8cee-7cc9c82f478a"

[[env.prod.kv_namespaces]]
binding = "session"
id = "db5f1e91a6e04562b78e2946de4b862e"
